### ISSUE TITLE
postgres syntax error on update

### ISSUE THREAD

**Issue by tallenaz** [SquareSquash/web#114]
Any ideas? Our squash app is at rails version is 4.0.8 and pg version is at 0.17.1

```
E, [2014-11-14T13:39:54.134882 #9512] ERROR -- : PG::SyntaxError: ERROR:  syntax error at or near ","
LINE 1: ...admin" = $1 WHERE "memberships"."user_id,project_id" = 1,12
                                                                   ^
: UPDATE "memberships" SET "admin" = $1 WHERE "memberships"."user_id,project_id" = 1, 12
F, [2014-11-14T13:39:54.145761 #9512] FATAL -- : 
ActiveRecord::StatementInvalid (PG::SyntaxError: ERROR:  syntax error at or near ","
LINE 1: ...admin" = $1 WHERE "memberships"."user_id,project_id" = 1, 12
                                                                   ^
: UPDATE "memberships" SET "admin" = $1 WHERE "memberships"."user_id,project_id" = 1, 12):
  app/controllers/project/memberships_controller.rb:108:in `update'
  app/middleware/ping.rb:29:in `call'
```

**Comment by RISCfuture** [comment]
Looks like an incompatibility between your version of ActiveRecord and composite_primsry_keys. Might want to play around with gem versions.
