### ISSUE TITLE
Bundle install fetch error. Update source of gem 'erector' and 'git'

### ISSUE THREAD

**Issue by amiit-github** [SquareSquash/web#121]
Change source of gem
------------------------------------------
erector gem
old -  git://github.com/RISCfuture/erector.git
new - git://github.com:RISCfuture/erector.git
ruby-git
git
old - git://github.com/RISCfuture/ruby-git.git
new - git://github.com:RISCfuture/ruby-git.git

**Comment by JasonBarnabe** [comment]
```
diff --git a/Gemfile.d/utilities.rb b/Gemfile.d/utilities.rb
index 83a3020..1378862 100644
--- a/Gemfile.d/utilities.rb
+++ b/Gemfile.d/utilities.rb
@@ -13,7 +13,7 @@
 #    limitations under the License.
 
 gem 'json'
-gem 'git', github: 'RISCfuture/ruby-git'
+gem 'git', git: 'https://github.com/schacon/ruby-git.git'
 gem 'user-agent'
 
 gem 'safe_yaml'
diff --git a/Gemfile.d/views.rb b/Gemfile.d/views.rb
index 46a4abb..7b8a098 100644
--- a/Gemfile.d/views.rb
+++ b/Gemfile.d/views.rb
@@ -12,5 +12,5 @@
 #    See the License for the specific language governing permissions and
 #    limitations under the License.
 
-gem 'erector', github: 'RISCfuture/erector'
+gem 'erector', git: 'https://github.com/erector/erector.git'
 gem 'kramdown'
```

**Comment by JasonBarnabe** [comment]
```ruby
diff --git a/Gemfile.d/authentication.rb b/Gemfile.d/authentication.rb
index 644fdd9..33e8805 100644
--- a/Gemfile.d/authentication.rb
+++ b/Gemfile.d/authentication.rb
@@ -13,5 +13,5 @@
 #    limitations under the License.
 
 conditionally('authentication.strategy', 'ldap') do
-  gem 'net-ldap', github: 'ruby-ldap/ruby-net-ldap', require: 'net/ldap'
+  gem 'net-ldap', git: 'https://github.com/ruby-ldap/ruby-net-ldap.git', require: 'net/ldap'
 end
```

**Comment by JasonBarnabe** [comment]
https://github.com/schacon/ruby-git.git does not have Git::Base#blame, which causes

```
E, [2017-03-09T10:09:25.542612 #8609] ERROR -- : /var/www/apps/squash_new/lib/blamer/cache.rb:56:in `git_blame'
/var/www/apps/squash_new/lib/blamer/cache.rb:40:in `blame'
/var/www/apps/squash_new/lib/blamer/recency.rb:100:in `block in blamed_revision'
/var/www/apps/squash_new/lib/blamer/recency.rb:99:in `map!'
/var/www/apps/squash_new/lib/blamer/recency.rb:99:in `blamed_revision'
/var/www/apps/squash_new/lib/blamer/recency.rb:76:in `bug_search_criteria'
/var/www/apps/squash_new/lib/blamer/base.rb:102:in `find_or_create_bug!'
/var/www/apps/squash_new/lib/workers/occurrences_worker.rb:88:in `perform'
/var/www/apps/squash_new/lib/workers/occurrences_worker.rb:45:in `perform'
/var/www/apps/squash_new/lib/background_runner/multithread.rb:31:in `block in run'
/var/www/apps/squash_new/lib/multithread.rb:64:in `spinoff'
/var/www/apps/squash_new/lib/background_runner/multithread.rb:31:in `run'
/var/www/apps/squash_new/lib/background_runner.rb:38:in `run'
/var/www/apps/squash_new/app/controllers/api/v1_controller.rb:63:in `notify'
```
RISCfuture/ruby-git no longer exists, but https://github.com/sandbender/ruby-git has this method.
