### ISSUE TITLE
ActionView::Template::Error in signup form

### ISSUE THREAD

**Issue by JasonBarnabe** [SquareSquash/web#127]
```
ActionView::Template::Error (wrong number of arguments (given 4, expected 5)):
    62:       def signup_form
    63:         div(class: 'row') do
    64:           div(class: 'two columns') { text! '&nbsp;' }
    65:           form_for(@user || User.new, url: signup_url, html: {class: 'eight columns whitewashed'}) do |f|
    66:             h3 "Don’t have an account yet?"
    67: 
    68:             input type: 'hidden', name: 'next', value: params[:next]
  app/views/sessions/new.html.rb:65:in `block in signup_form'
  app/views/sessions/new.html.rb:63:in `signup_form'
  app/views/sessions/new.html.rb:35:in `block (2 levels) in body_content'
  app/views/sessions/new.html.rb:32:in `block in body_content'
  app/views/layouts/application.html.rb:81:in `block (4 levels) in modal_section'
  app/views/layouts/application.html.rb:81:in `block (3 levels) in modal_section'
  app/views/layouts/application.html.rb:79:in `block (2 levels) in modal_section'
  app/views/layouts/application.html.rb:78:in `block in modal_section'
  app/views/layouts/application.html.rb:77:in `modal_section'
  app/views/sessions/new.html.rb:30:in `body_content'
  app/views/layouts/application.html.rb:161:in `block in body_portion'
  app/views/layouts/application.html.rb:148:in `body_portion'
  app/views/layouts/application.html.rb:27:in `block in content'
  app/views/layouts/application.html.rb:25:in `content'
  app/views/sessions/new.html.rb:1:in `_app_views_sessions_new_html_rb__159209451951245326_27606700'
  app/middleware/ping.rb:29:in `call'
```

**Comment by JasonBarnabe** [comment]
https://github.com/erector/erector/issues/69
